apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: smplverse-metadata
build:
  artifacts:
  - image: piotrostr/metadata
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - manifest.yaml
