name: "CI/CD"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang
    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Install dependencies
      run: go get -u ./...

    - name: Build
      run: go build ./...

  lint:
    runs-on: ubuntu-latest
    container: golang
    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Install dependencies
      run: go get -u ./...

    - name: Install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin v1.46.2

    - name: Run vet & lint
      run: |
        go vet ./...
        golangci-lint run

  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3

    - name: Check out
      uses: actions/checkout@v3

    - name: Install dependencies
      run: go get -u ./...

    - name: Run tests
      run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
      env:
        REDIS_HOST: redis

    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
