name: "CI/CD"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Install dependencies
      run: go get -u golang.org/x/lint/golint
        
    - name: Build
      run: go build ./...
      
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Install dependencies
      run: go get -u golang.org/x/lint/golint
        
    - name: Run vet & lint
      run: |
        go vet ./...
        golint ./...


  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        go mod tidy

    - name: Run tests
      run: go test  -coverprofile=c.out -covermode=atomic ./...

    - name: Upload coverage report
      uses: codecov/codecov-action@v1.0.2
      with:
        file: ./c.out
        flags: unittests
        name: codecov-umbrella
